apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: events-db
spec:
  serviceName: "events-db"
  replicas: 1
  selector:
    matchLabels:
      app: events-db
  template:
    metadata:
      labels:
        app: events-db
    spec:
      containers:
        - name: events-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: events-config
            - secretRef:
                name: events-secret
          volumeMounts:
            - name: events-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: events-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
