apiVersion: v1
kind: Secret
metadata:
  name: events-secret
type: Opaque
stringData:
  # The entire URLs are stored directly here as fully resolved strings.
  # This completely prevents messy YAML logic in your Deployment.
  MONGO_URI: "mongodb://root:password@events-db:27017/"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  
  # Variables required by the official mongo:latest Docker image
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
