apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
data:
  PORT: "8004"
  DATABASE_URL: postgresql://user:password@payment-db:5432/payment_db
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  BOOKING_SERVICE_URL: http://booking-service:8003
  TICKET_SERVICE_URL: http://ticket-service:8005